import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <html lang="en">
      <body className={inter.className}>
      <header style={{width:'100%',height:'50px',backgroundColor:'pink'}}> Header</header>

        {children}

        <footer style={{width:'100%',height:'50px',backgroundColor:'pink'}}> Footer</footer>

        </body>
    </html>
    </>
  );
}
